spring:
  application:
    name: algorecall-server

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://host.containers.internal:5432/algorecall
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        default_schema: public
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    enabled: true

server:
  port: 8080

app:
  timezone: ${APP_TIMEZONE:Asia/Kolkata}
  frontend-url: ${APP_FRONTEND_URL:https://algo-recall-seven.vercel.app}
  jwt:
    secret: ${JWT_SECRET:}
    expiration-ms: 2592000000
  import:
    enabled: true
  notification:
    reminder-minutes: 30
  google:
    calendar:
      enabled: true
      client-id: ${GOOGLE_CLIENT_ID:}
      client-secret: ${GOOGLE_CLIENT_SECRET:}
  firebase:
    enabled: true
    credentials-json: ${FIREBASE_CREDENTIALS:}
  twilio:
    enabled: ${TWILIO_ENABLED:false}
    account-sid: ${TWILIO_ACCOUNT_SID:}
    auth-token: ${TWILIO_AUTH_TOKEN:}
    from-number: ${TWILIO_FROM_NUMBER:}
